version: "3"
services:
    php-fpm:
        build: install/php-fpm
        ports:
            - 9010:9000
        volumes:
            - ./code:/var/www/html/
            - ./install/php-fpm/php.ini:/usr/local/etc/php/php.ini
        links:
            - db
    nginx:
        build: install/nginx
        ports:
            - 8080:80
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
    db:
        image: mysql:5.6
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_DATABASE: wp_aws
            MYSQL_USER: mng
            MYSQL_PASSWORD: Fds123..!!
            MYSQL_ROOT_PASSWORD: Fds123..!!
            BIND-ADDRESS: 0.0.0.0
        volumes:
            - MysqlVolume:/var/lib/mysql
volumes:
  MysqlVolume:
